version: "3.9"

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  # cerebellum:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: Cerebellum2
  #   ports:
  #     - "8001:8001"
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - REDIS_ENDPOINT_ADDRESS=redis
  #     - REDIS_ENDPOINT_PORT=6379
  #     - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
  #     - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
  #     - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
  #     - AWS_REGION=us-east-1
  #     - API_KEY=sample key
  #     - DYNAMODB_MESSAGES_TABLE_NAME=messages
  #     - DYNAMODB_CHANNELS_TABLE_NAME=channels
  #   depends_on:
  #     - dynamodb-local
  #     - redis
